# Generated by Django 3.2.7 on 2021-09-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
