# Generated by Django 3.2.7 on 2021-09-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Компании', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AddField(
            model_name='company',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
