# Generated by Django 3.2.7 on 2021-09-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210913_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
    ]
